### ISSUE TITLE
Markers appear below line intersections in ruler

### ISSUE THREAD

**Issue by mattixpet** [korywka/mapbox-controls#56]
Does anyone have any idea what's going on here?

![image](https://github.com/korywka/mapbox-controls/assets/9594934/702a8abb-7752-48d5-8d17-aeedd1492d60)

Something with the projection perhaps?

We are using tiles with epsg3857 projection, this is the map style:

```javascript
export const mapStyle: MapStyle = {
  version: 8,
  sources: {
    "raster-tiles": {
      type: "raster",
      tiles: ["https://geo.vedur.is/geoserver/www/imo_basemap_epsg3857/{z}/{x}/{y}.png"],
      tileSize: 256,
      maxzoom: 14,
    },
  },
  glyphs: "fonts/{fontstack}/{range}.pbf",
  layers: [
    {
      id: "simple-tiles",
      type: "raster",
      source: "raster-tiles",
    },
  ],
};
```

I would really like to use this plugin, since it is really nice, so any help is appreciated. I'm hoping I can just set the projection somehow or match it. Perhaps it's possible in Maplibre itself, but I haven't found anything yet. I am inclined to think it has something to do with this plugin though, since for example I used another [plugin](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/) which draws polygons, and that was no problem.

I am also using react-maplibre.

**Comment by korywka** [comment]
Hello. Can you please drop your minimal example to reproduce at https://codesandbox.io/ or similar? Maybe just zip file is ok too. This will give me more time to fix and not to find out how to reproduce 🙌

**Comment by mattixpet** [comment]
I will do that soon, thank you

**Comment by korywka** [comment]
@mattixpet ah the reason is globe projection. found the issue with this bug https://github.com/mapbox/mapbox-gl-js/issues/12592
ruler lines are geojson lines, but markers are CSS positioned elements (`div`). and at some point this globe to CSS projection calculation is broken.
all i can do here is to draw circle not with html marker, but with geojson circle. but in this case drag n drop for markers should be implemented from scratch (to make current markers dragable we need just to set config option).

**Comment by korywka** [comment]
@mattixpet please try v2. Options for ruler control are breaking changes, cause switched from `mapboxgl.Marker` to `circle` layer. Should help. Please let me know if you still have this problem.

**Comment by mattixpet** [comment]
Just to confirm: this completely solved the issue for me. Thank you for an extremely speedy solution.
